#!/bin/sh

_cups_path1=/usr/share/ppd
_cups_path2=/usr/share/cups/model
ppd_files="canone480.ppd canonmb2100.ppd canonmg3000.ppd canonmb5400.ppd canong4000.ppd canonip110.ppd canonmg5700.ppd canonmg6600.ppd canonmb5100.ppd canonib4100.ppd canonmx490.ppd canonmg3600.ppd canone460.ppd canonts6000.ppd canonmg7500.ppd canonmg6800.ppd canonmg7700.ppd canonmb5300.ppd canonmb2700.ppd canonts5000.ppd canong3000.ppd canonmg6900.ppd canone470.ppd canonts9000.ppd canonmg5600.ppd canonmb2300.ppd canonts8000.ppd canonmg2900.ppd canonmb5000.ppd canonmb2000.ppd canonib4000.ppd "

if [ -x /sbin/ldconfig ]; then
	/sbin/ldconfig
fi
# make symbolic link for ppd
if [ ! -d ${_cups_path2} ]; then
	mkdir ${_cups_path2}
fi
for f in ${ppd_files}; do
	ln -fs ${_cups_path1}/${f} ${_cups_path2}/${f}
done
