#!/bin/sh

_cups_path2=/usr/share/cups/model
ppd_files="canone480.ppd canonip110.ppd canonmg5700.ppd canonmg6600.ppd canonmx490.ppd canonmg3600.ppd canone460.ppd canonmg7500.ppd canonmg6800.ppd canonmg7700.ppd canonmb5300.ppd canonmg6900.ppd canonmg5600.ppd canonmb2300.ppd canonmg2900.ppd canonmb5000.ppd canonmb2000.ppd canonib4000.ppd "

if [ -x /sbin/ldconfig ]; then
	/sbin/ldconfig
fi
# remove cnbp* libs
for LIBS in libcnnet2 libcnbpcnclapicom2
do
	if [ -h /usr/lib/${LIBS}.so ]; then
		rm -f /usr/lib/${LIBS}.so
	fi	
done
if [ "$1" = 0 ] ; then
	rmdir -p --ignore-fail-on-non-empty /usr/lib/bjlib
fi
# remove symbolic link for ppd
for f in ${ppd_files}; do
	rm -f ${_cups_path2}/${f}
done
